### ISSUE TITLE
Homer v5.9 - Docker container for heplify is not available...

### ISSUE THREAD

**Issue by paxinos** [QXIP/rancher-catalog#4]
Docker container is not available - 

Failed to pull image "negbie/heplify-server:latest": rpc error: code = Unknown desc = Error response from daemon: pull access denied for negbie/heplify-server, repository does not exist or may require 'docker login'

**Comment by lmangani** [comment]
Hi @paxinos this version is obsolete the latest release is 7.7 and older images might be outdated or abandoned - this said replace `negbie` with `sipcapture` and it should pull.

**Comment by paxinos** [comment]
Thanks!  Actually just got that working a couple minutes ago.

Any chance of a helm chart for 7.7 anytime soon?
